### ISSUE TITLE
Build error on windows 7

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#1942]
Getting the below build error on windows. `$ GNU bash, version 3.1.20(4)-release (i686-pc-msys)`

```
wh@GRIME /d/dev/ractive (dev)
$ npm run build

> ractive@0.7.3 build d:\dev\ractive
> sh ./scripts/build.sh

> linting...
> emptying tmp dir...
> building Ractive...
gobble: 02-babel done in 16075ms
gobble: 02-babel done in 16075ms
gobble: 02-babel done in 16075ms
gobble: 02-babel done in 16075ms
gobble: 02-babel done in 16075ms
gobble: 02-babel done in 16075ms
gobble: 03-esperantoBundle done in 1883ms
gobble: 07-sorcery done in 1289ms
gobble: 04-esperantoBundle done in 1748ms
gobble: 08-sorcery done in 1021ms
gobble: 05-esperantoBundle done in 1294ms
gobble: 09-sorcery done in 790ms
gobble: 06-esperantoBundle done in 1280ms
gobble: 10-sorcery done in 817ms
gobble: 24-merge done in 26ms
gobble: 11-moveTo done in 12ms
gobble: 11-moveTo done in 12ms
gobble: 12-merge done in 13ms
gobble: 12-merge done in 13ms
∙∙∙∙∙◦∙ 13-babel running...
gobble: Uncaught, unspecified 'error' event.
>>>
Error: Uncaught, unspecified 'error' event.
    at EventEmitter.emit (d:\dev\ractive\node_modules\gobble\node_modules\eventemitter2\lib\eventemitter2.js:292:17)
    at d:\dev\ractive\node_modules\gobble\lib\nodes\build\index.js:50:8
    at lib$es6$promise$$internal$$tryCatch (d:\dev\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:319:16)
    at lib$es6$promise$$internal$$invokeCallback (d:\dev\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:331:17)
    at lib$es6$promise$$internal$$publish (d:\dev\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:302:11)
    at lib$es6$promise$$internal$$publishRejection (d:\dev\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:252:7)
    at lib$es6$promise$asap$$flush (d:\dev\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:113:9)
    at process._tickCallback (node.js:355:11)
<<<
```

I added a console.log around `d:\dev\ractive\node_modules\gobble\lib\nodes\build\index.js:50:8` which corresponds roughly to: [this line in gobble](https://github.com/gobblejs/gobble/blob/master/src/nodes/build/index.js#L65). The value of `err` was `{aborted: true}`. After some searching it seems that some file change notifications are causing the abort around [here](https://github.com/gobblejs/gobble/blob/master/src/nodes/Transformer.js#L142).

I `console.log`'d the `changes` array and it spit this out (more than once) before the above error/stacktrace.
```
[ { type: 'change',
    path: 'd:\\dev\\ractive\\test\\testdeps\\samples\\mustache-spec\\comments.js
on',
    changed: true },
  { type: 'change',
    path: 'd:\\dev\\ractive\\test\\testdeps\\samples\\mustache-spec\\delimiters.
json',
    changed: true },
<snip rest of files in mustache-spec dir> ]
```

This is where I'm stuck due to unfamiliarity with gobble et al. I ran Procmon and no other process is accessing the files in this directory. (These change notifications don't happen on my linux vm where the build completed.)

If someone can provide guidance I would appreciate it.

**Comment by Madgvox** [comment]
I've run into the same issue, where it will get stuck in a `build restarting` loop.  I doubt that there's something special about the `mustache-spec` folder that's causing the issue, as the same issue occurred when I attempted to build the 'learn.ractivejs.org' repo.

**Comment by woodlandhunter** [comment]
This error no longer occurs for me
