### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2148]
On dev branch:

Due to part of a windows path being used directly as the module name around [here](https://github.com/ractivejs/ractive/blob/dev/gobblefile.js#L145), an unescaped backslash is being used in the module name, which causes acorn to choke on that string (e.g `initModule('methods\updateModel.js' );`)

```
Bad character escape sequence (2:21)
SyntaxError: Bad character escape sequence (2:21)
    at Parser.pp.raise (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:975:13)
    at Parser.pp.readHexChar (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:3064:24)
    at Parser.pp.readCodePoint (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:2927:17)
    at Parser.pp.readEscapedChar (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:3024:37)
    at Parser.pp.readString (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:2949:19)
    at Parser.pp.getTokenFromCode (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:2732:19)
    at Parser.pp.readToken (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:2477:15)
    at Parser.pp.nextToken (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:2469:71)
    at Parser.pp.next (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:2418:8)
    at Parser.pp.eat (C:\dev\ractive\node_modules\rollup\node_modules\acorn\dist\acorn.js:1460:10)
<<<
```

I was able to get the build to continue by doing a .replace(), but I'm not sure if the problem should be fixed farther up.

**Comment by Rich-Harris** [comment]
Replacing the back-slashes *should* work... hopefully 6be11c1ba4ad9ccf4868a1eb9fd93d9452f5b6de fixes it?

**Comment by woodlandhunter** [comment]
@Rich-Harris Thanks. This got me to the tests, which now fail. (Which I don't remember happening when I posted this initially):

```
> running tests...
> running node.js-specific tests. working directory is /c/dev/ractive
C:\dev\ractive\tmp\ractive.js:2233
        Child.prototype = create(Parent.prototype);
                          ^
TypeError: undefined is not a function
    at Function.Parser.extend (C:\dev\ractive\tmp\ractive.js:2233:22)
    at C:\dev\ractive\tmp\ractive.js:2248:29
    at namespaces.get (C:\dev\ractive\tmp\ractive.js:13:83)
    at Object.<anonymous> (C:\dev\ractive\tmp\ractive.js:16:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\dev\ractive\tmp\test\node-tests\basic.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\dev\ractive\tmp\test\node-tests\index.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\dev\ractive\node_modules\mocha\lib\mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\dev\ractive\node_modules\mocha\lib\mocha.js:213:14)
    at Mocha.run (C:\dev\ractive\node_modules\mocha\lib\mocha.js:453:10)
    at Object.<anonymous> (C:\dev\ractive\node_modules\mocha\bin\_mocha:393:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

`create` is imported at the top of Parser.js, so not sure what the deal is.. I'll check into it later if needed..

**Comment by Rich-Harris** [comment]
I'm seeing the same error in Travis: https://travis-ci.org/ractivejs/ractive/builds/81663643. It's unrelated to this change (I restarted a previous successful build, same error). But it builds fine locally (on OS X). Really weird...

**Comment by Rich-Harris** [comment]
Looks like this is a bug recently introduced to Rollup – modules are being bundled in the wrong order. Looking into it

**Comment by heavyk** [comment]
could it be due to an import not yet being made available? I get this often when I have circular dependencies. usually an exported object instantiation which uses an import

**Comment by heavyk** [comment]
whoops... didn't see your comment :) carry on..
