### ISSUE TITLE
Node.js-compatible tests

### ISSUE THREAD

**Issue by ElliotChong** [ractivejs/ractive#286]
I've taken an initial swipe at implementing Node.js tests using Mocha and the existing Qunit tests as a base.

Commit @: https://github.com/ElliotChong/Ractive/commit/84e25be908b46e8b829493ca1c6d4ad9f3314fbf

Most of the tests were straight-forward to port; however, ```misc``` has been temporarily commented out since that needs a good comb-over for tests that don't make sense in the Node.js environment- basically, anything to do with events or modifying data. Also, ```events``` is being omitted since that whole suite doesn't apply to serverside rendering.

Currently most of the tests are passing just fine; however, there are two use-cases which seem to be throwing errors and I'm not sure yet if it's a test implementation issue or a Node.js-specific issue.
  
  
**First Set of Errors**
I'm not sure if these discrepancies are because of Node.js or jsdom... Need to look into it.
```
  1) Mustache compliance (Comments) Standalone Line Endings:

      actual expected

      |<CR><LF>
      <LF>
      |



  2) Mustache compliance (Delimiters) Standalone Line Endings:

      actual expected

      |<CR><LF>
      <LF>
      |



  3) Mustache compliance (Partials) Standalone Line Endings:

      actual expected

      |<CR><LF>
      <LF>
      &gt;|
```
  
  
**Second Set of Errors**
```
  4) Render List section with non-self-updating attributes:
     TypeError: Cannot call method 'appendChild' of undefined
      at Object.DomSection.render (./Ractive/tmp/Ractive.js:2533:36)
      at Object.lessThan [as update] (./Ractive/tmp/Ractive.js:2104:22)
      at notifyDependantsAtPriority (./Ractive/tmp/Ractive.js:281:29)
      at Function.notifyDependants.multiple (./Ractive/tmp/Ractive.js:265:25)
      at set (./Ractive/tmp/Ractive.js:821:30)
      at Context.<anonymous> (./Ractive/test/mocha/render.js:424:11)
      at Test.Runnable.run (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runnable.js:211:32)
      at Runner.runTest (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:358:10)
      at ./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:404:12
      at next (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:284:14)

  5) Render Section with non-explicitly-closed element:
     TypeError: Cannot call method 'appendChild' of undefined
      at Object.DomSection.render (./Ractive/tmp/Ractive.js:2533:36)
      at Object.lessThan [as update] (./Ractive/tmp/Ractive.js:2104:22)
      at notifyDependantsAtPriority (./Ractive/tmp/Ractive.js:281:29)
      at Function.notifyDependants.multiple (./Ractive/tmp/Ractive.js:265:25)
      at set (./Ractive/tmp/Ractive.js:821:30)
      at Context.<anonymous> (./Ractive/test/mocha/render.js:424:11)
      at Test.Runnable.run (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runnable.js:211:32)
      at Runner.runTest (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:358:10)
      at ./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:404:12
      at next (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:284:14)

  6) Render Expression with implicit iterator:
     TypeError: Cannot call method 'appendChild' of undefined
      at Object.DomSection.render (./Ractive/tmp/Ractive.js:2533:36)
      at Object.lessThan [as update] (./Ractive/tmp/Ractive.js:2104:22)
      at notifyDependantsAtPriority (./Ractive/tmp/Ractive.js:281:29)
      at Function.notifyDependants.multiple (./Ractive/tmp/Ractive.js:265:25)
      at set (./Ractive/tmp/Ractive.js:821:30)
      at Context.<anonymous> (./Ractive/test/mocha/render.js:424:11)
      at Test.Runnable.run (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runnable.js:211:32)
      at Runner.runTest (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:358:10)
      at ./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:404:12
      at next (./Ractive/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:284:14)
```
Referenced line (2533):
```
this.pNode.appendChild(this.docFrag);
```

I'm not sure why Ractive is blowing up here on Node, is it expecting pNode to be a DOM element? I was under the impression pNode should be Ractive shadow-dom.

If you have a chance to look over the tests and have any feedback it'd be much appreciated. Thanks!

**Comment by mrjoelkemp** [comment]
Safe to close? It's been a year.
