### ISSUE TITLE
Uncaught ParserError: Expected matching quote ''' class-open='{{.open}}

### ISSUE THREAD

**Issue by sarendipitee** [ractivejs/ractive#3077]
## Description:

Using a class-*<class>* attr throws parse error. Fiddle below.

```
"Error: Expected matching quote ''' at line 3 character 15:
   class-open='{{.open}}'
               ^----
    at ParseError (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:5191:9)
    at Child.error (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:5307:15)
    at readArguments (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:6880:57)
    at readAttributeOrDirective (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:6813:3)
    at readMustache (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:6910:14)
    at Array.readElement$1 (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:7822:22)
    at Child.read (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:5242:29)
    at Array.readTemplate (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:8126:29)
    at Child.read (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:5242:29)
    at Child.Parser (https://unpkg.com/ractive@1.0.0-build-64/ractive.js:5220:58)"
```

## Versions affected:
0.9+
## Platforms affected:
All
## Reproduction:

```
const RactiveDropdown = Ractive.extend({
	template: `
  <div class='ractive-dropdown {{.class}}'
	 class-open='{{.open}}'
   on-click='click'
	 on-hover='hover'
	 {{#if .style}}style='{{.style}}'{{/if}}>

	{{yield}}

	</div>
  `,
});

const r = window.r = new Ractive({
  el: '#main',
  template: `<dropdown></dropdown>`,
  data: {
  	who: 'World'
  },
  components: {
  	dropdown: RactiveDropdown
  }
});
```

https://jsfiddle.net/wrrvpp9v/

**Comment by marcalexiei** [comment]
In 0.9.x + version `{{...}}` syntax in class- attributes have been deprecated:

From [changelog](https://github.com/ractivejs/ractive/blob/dev/CHANGELOG.md#090)

> class- directives are now parsed in an expression context, meaning that mustaches are no longer required. This normalizes templates into two categories: stringy things that require mustaches, and value things that don't. The style- directive remains in the stringy category.

You should use 
```
class-open='.open'
```

https://jsfiddle.net/wrrvpp9v/2/

I hope this helps!

**Comment by evs-chris** [comment]
Sorry, normalizing strings vs values :(

I promise it won't break again, though.

**Comment by sarendipitee** [comment]
Lord have mercy
